CREATE DATABASE db_3s
GO

USE db_3s;
GO

--TIPO USUARIO
CREATE TABLE TipoUsuario(
	IdTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(15) NOT NULL
);
GO

--CARGO
CREATE TABLE Cargo(
	IdCargo TINYINT PRIMARY KEY IDENTITY,
	Cargo VARCHAR(15) NOT NULL
);
GO

--TIPO MARCACAO
CREATE TABLE tipoMarcacao(
	IdTipoMarcacao TINYINT PRIMARY KEY IDENTITY,
	tipoMarcacao VARCHAR(15) NOT NULL
);
GO

--USUARIO
CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoUsuario TINYINT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario) NOT NULL,
	Nome VARCHAR(20) NOT NULL,
	Email VARCHAR(256) NOT NULL,
	Senha VARCHAR(9) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	QrCode VARCHAR(64) NOT NULL,
);
GO

--FUNCIONARIO
CREATE TABLE Funcionario(
	IdFuncionario INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	IdCargo TINYINT FOREIGN KEY REFERENCES Cargo(IdCargo) NOT NULL,
	EmailEmpresarial VARCHAR(256) NOT NULL,
	ativo BIT NOT NULL,
);
GO

--MARCACAO
CREATE TABLE Marcacao(
	IdMarcacao BIGINT PRIMARY KEY IDENTITY,
	IdTipoMarcacao TINYINT FOREIGN KEY REFERENCES TipoMarcacao(IdTipoMarcacao) NOT NULL,
	IdFuncionario INT FOREIGN KEY REFERENCES Funcionario(IdFuncionario) NOT NULL,
	DataHora DATETIME NOT NULL,
);
GO